### ISSUE TITLE
Cheat doesnt work...

### ISSUE THREAD

**Issue by M4vm** [iBelg/idleon-cheat#5]
Whenever i inject it and type something in the console it just says "undefined" ... I tried reinstalling my game and it wont work ... can anyone help me fix it ?

**Comment by Boordfles** [comment]
Did you drag all files into the install folder?
Are you loaded into a character and not just on the character selection screen?

**Comment by M4vm** [comment]
> 

What do you mean by that ? I put the cheat , main.js and cheats.js all in my Idleon game folder and it doesnt work... Im also using my first character from the selection screen. Can you maybe please explain it a little bit better ?

**Comment by M4vm** [comment]
Nevermind, im just stupid
