### ISSUE TITLE
What does 'quickref' do?

### ISSUE THREAD

**Issue by Boordfles** [iBelg/idleon-cheat#6]
I figured out the other stuff easy but still unsure what quickref is

If Dev would also like, I can write up a quick-use guide they can copy-paste into the description to help users with questions.
Just lmk, wouldn't be a problem and you wouldn't have to give credit lol

**Comment by M4vm** [comment]
quickref is used to quickly refine stuff i think... btw i cant pickup items i drop using the drop command , can you help ?

**Comment by sloth7265** [comment]
What does it mean? can you send me what the other cheats mean? sloth#1983

**Comment by iBelg** [comment]
While quickref is active you can use your bank from anywhere (using quickref to access it).
