### ISSUE TITLE
I keep getting errors

### ISSUE THREAD

**Issue by jul358** [iBelg/idleon-cheat#7]
It says their is no such file or directory and I Think it tells me to open it? But I am not sure. Then it says use inject cheats Trace-warnings which I literally cant find at all. It also tells me Unhandles promise rejections. This error originated either by throwing inside async function without a catch block, or by rejecting a promise which was not handles with .catch(). and then it tells me to use a CLI Flag?

**Comment by sir-blorps** [comment]
Did you also download the 'cheats.js' from the code page? It isn't on the release page, it's on the "Code" page.

**Comment by iBelg** [comment]
Tested this tool in the latest version of the game and everything works on my end.
